### ISSUE TITLE
Adding relevant tags on readme to drive rollup 

### ISSUE THREAD

**Issue by agowdamsft** [Azure-Samples/durablefunctions-mapreduce-dotnet#5]
Need to add relevant tags to make this sample roll up into new https://review.docs.microsoft.com/en-us/samples/browse/?branch=master&products=azure-functions

**Comment by brandonh-msft** [comment]
from your link:
![image](https://user-images.githubusercontent.com/20270743/62392059-45b8e380-b51b-11e9-8494-44e94929407d.png)
I don't think `tags` is needed anymore.
